package config

import (
	"os"
	"testing"
)

func TestLoadFromEnv_AllSet(t *testing.T) {
	envVars := map[string]string{
		"PROXY_PORT":          "9000",
		"N8N_BACKEND_URL":     "http://nginx:80",
		"N8N_INTERNAL_URL":    "http://n8n:5678",
		"OIDC_ISSUER_URL":     "http://keycloak/realms/test",
		"OIDC_CLIENT_ID":      "test-client",
		"OIDC_CLIENT_SECRET":  "test-secret",
		"OIDC_REDIRECT_URL":   "http://localhost:9000/auth/callback",
		"SESSION_MAX_AGE":     "7200",
		"KEYCLOAK_GROUP_PREFIX": "/test-",
		"N8N_TEAM_CREDENTIALS": `{"team1":{"email":"t1@local","pass":"p1"}}`,
		"COOKIE_TTL":          "600",
		"DANGEROUS_NODES":     "n8n-nodes-base.code,n8n-nodes-base.ssh",
	}

	for k, v := range envVars {
		os.Setenv(k, v)
	}
	defer func() {
		for k := range envVars {
			os.Unsetenv(k)
		}
	}()

	cfg, err := LoadFromEnv()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if cfg.ProxyPort != 9000 {
		t.Errorf("expected port 9000, got %d", cfg.ProxyPort)
	}
	if cfg.N8NBackendURL != "http://nginx:80" {
		t.Errorf("unexpected backend URL: %s", cfg.N8NBackendURL)
	}
	if cfg.OIDCIssuerURL != "http://keycloak/realms/test" {
		t.Errorf("unexpected OIDC issuer: %s", cfg.OIDCIssuerURL)
	}
	if cfg.OIDCClientID != "test-client" {
		t.Errorf("unexpected client ID: %s", cfg.OIDCClientID)
	}
	if cfg.SessionMaxAge != 7200 {
		t.Errorf("expected session max age 7200, got %d", cfg.SessionMaxAge)
	}
	if cfg.KeycloakGroupPrefix != "/test-" {
		t.Errorf("unexpected group prefix: %s", cfg.KeycloakGroupPrefix)
	}
	if cfg.CookieTTL != 600 {
		t.Errorf("expected cookie TTL 600, got %d", cfg.CookieTTL)
	}
	if len(cfg.DangerousNodes) != 2 {
		t.Errorf("expected 2 dangerous nodes, got %d", len(cfg.DangerousNodes))
	}
	if len(cfg.TeamCredentials) != 1 {
		t.Errorf("expected 1 team credential, got %d", len(cfg.TeamCredentials))
	}
	cred, ok := cfg.TeamCredentials["team1"]
	if !ok {
		t.Fatal("expected team1 in credentials")
	}
	if cred.Email != "t1@local" {
		t.Errorf("expected t1@local, got %s", cred.Email)
	}
}

func TestLoadFromEnv_MissingIssuerURL(t *testing.T) {
	os.Setenv("OIDC_ISSUER_URL", "")
	os.Setenv("OIDC_CLIENT_SECRET", "secret")
	defer func() {
		os.Unsetenv("OIDC_ISSUER_URL")
		os.Unsetenv("OIDC_CLIENT_SECRET")
	}()

	_, err := LoadFromEnv()
	if err == nil {
		t.Error("expected error for missing OIDC_ISSUER_URL")
	}
}

func TestLoadFromEnv_MissingClientSecret(t *testing.T) {
	os.Setenv("OIDC_ISSUER_URL", "http://keycloak/realms/test")
	os.Setenv("OIDC_CLIENT_SECRET", "")
	defer func() {
		os.Unsetenv("OIDC_ISSUER_URL")
		os.Unsetenv("OIDC_CLIENT_SECRET")
	}()

	_, err := LoadFromEnv()
	if err == nil {
		t.Error("expected error for missing OIDC_CLIENT_SECRET")
	}
}

func TestLoadFromEnv_Defaults(t *testing.T) {
	os.Setenv("OIDC_ISSUER_URL", "http://keycloak/realms/test")
	os.Setenv("OIDC_CLIENT_SECRET", "secret")
	// Clear other values to test defaults
	os.Unsetenv("PROXY_PORT")
	os.Unsetenv("OIDC_CLIENT_ID")
	os.Unsetenv("KEYCLOAK_GROUP_PREFIX")
	os.Unsetenv("SESSION_MAX_AGE")
	os.Unsetenv("COOKIE_TTL")
	os.Unsetenv("N8N_TEAM_CREDENTIALS")
	os.Unsetenv("ENABLE_VAULT")
	defer func() {
		os.Unsetenv("OIDC_ISSUER_URL")
		os.Unsetenv("OIDC_CLIENT_SECRET")
	}()

	cfg, err := LoadFromEnv()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if cfg.ProxyPort != 8443 {
		t.Errorf("expected default port 8443, got %d", cfg.ProxyPort)
	}
	if cfg.OIDCClientID != "n8n-proxy" {
		t.Errorf("expected default client ID n8n-proxy, got %s", cfg.OIDCClientID)
	}
	if cfg.KeycloakGroupPrefix != "/n8n-prod-" {
		t.Errorf("expected default prefix /n8n-prod-, got %s", cfg.KeycloakGroupPrefix)
	}
	if cfg.SessionMaxAge != 3600 {
		t.Errorf("expected default session age 3600, got %d", cfg.SessionMaxAge)
	}
	if cfg.CookieTTL != 3600 {
		t.Errorf("expected default cookie TTL 3600, got %d", cfg.CookieTTL)
	}
	if cfg.EnableVault != false {
		t.Error("expected default EnableVault false")
	}
}

func TestLoadFromEnv_InvalidTeamCredentialsJSON(t *testing.T) {
	os.Setenv("OIDC_ISSUER_URL", "http://keycloak/realms/test")
	os.Setenv("OIDC_CLIENT_SECRET", "secret")
	os.Setenv("N8N_TEAM_CREDENTIALS", "invalid-json{{{")
	defer func() {
		os.Unsetenv("OIDC_ISSUER_URL")
		os.Unsetenv("OIDC_CLIENT_SECRET")
		os.Unsetenv("N8N_TEAM_CREDENTIALS")
	}()

	_, err := LoadFromEnv()
	if err == nil {
		t.Error("expected error for invalid team credentials JSON")
	}
}

func TestLoadFromEnv_AutoGeneratedRedirectURL(t *testing.T) {
	os.Setenv("OIDC_ISSUER_URL", "http://keycloak/realms/test")
	os.Setenv("OIDC_CLIENT_SECRET", "secret")
	os.Unsetenv("OIDC_REDIRECT_URL")
	os.Unsetenv("PROXY_PORT")
	defer func() {
		os.Unsetenv("OIDC_ISSUER_URL")
		os.Unsetenv("OIDC_CLIENT_SECRET")
	}()

	cfg, err := LoadFromEnv()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expected := "http://localhost:8443/auth/callback"
	if cfg.OIDCRedirectURL != expected {
		t.Errorf("expected auto-generated redirect URL %s, got %s", expected, cfg.OIDCRedirectURL)
	}
}

func TestGetEnv(t *testing.T) {
	os.Setenv("TEST_KEY", "value")
	defer os.Unsetenv("TEST_KEY")

	if v := getEnv("TEST_KEY", "default"); v != "value" {
		t.Errorf("expected value, got %s", v)
	}
	if v := getEnv("NONEXISTENT_KEY", "default"); v != "default" {
		t.Errorf("expected default, got %s", v)
	}
}

func TestGetEnvInt(t *testing.T) {
	os.Setenv("TEST_INT", "42")
	defer os.Unsetenv("TEST_INT")

	if v := getEnvInt("TEST_INT", 0); v != 42 {
		t.Errorf("expected 42, got %d", v)
	}
	if v := getEnvInt("NONEXISTENT_INT", 99); v != 99 {
		t.Errorf("expected 99, got %d", v)
	}

	os.Setenv("TEST_INT_BAD", "not-a-number")
	defer os.Unsetenv("TEST_INT_BAD")
	if v := getEnvInt("TEST_INT_BAD", 10); v != 10 {
		t.Errorf("expected default 10 for bad int, got %d", v)
	}
}

func TestGetEnvBool(t *testing.T) {
	os.Setenv("TEST_BOOL_TRUE", "true")
	os.Setenv("TEST_BOOL_FALSE", "false")
	defer func() {
		os.Unsetenv("TEST_BOOL_TRUE")
		os.Unsetenv("TEST_BOOL_FALSE")
	}()

	if v := getEnvBool("TEST_BOOL_TRUE", false); v != true {
		t.Error("expected true")
	}
	if v := getEnvBool("TEST_BOOL_FALSE", true); v != false {
		t.Error("expected false")
	}
	if v := getEnvBool("NONEXISTENT_BOOL", true); v != true {
		t.Error("expected default true")
	}
}
